settings:
  title: "Soap's Status Page"
  url: 'https://status.itssoap.ninja' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: anidl-org # unique identifier
    name: AniDL
    description: 'AniDL main website.' # default=empty
    url: 'https://anidl.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: rain
    name: Rain Ongoing
    description: "Rain's Ongoing Index."
    url: 'https://ongoing.rain11.workers.dev/'
    method: GET
    expectStatus: 200

  - id: rain
    name: Rain BD
    description: "Rain's BD Index."
    url: 'https://raindrive.rain11.workers.dev/'
    method: GET
    expectStatus: 200
    
  - id: zoro
    name: Zoro
    description: "Zoro's Index."
    url: 'https://mydrive.zk3.workers.dev/'
    method: GET
    expectStatus: 200
    
  - id: gods
    name: GodsEmperor
    description: "God's Index."
    url: 'https://godsdrive.godsemperor1.workers.dev/'
    method: GET
    expectStatus: 200
    
  - id: zero
    name: XeZero
    description: "Zero's Index."
    url: 'https://ownl.icu/'
    method: GET
    expectStatus: 200
    
  - id: zero1
    name: XeZero PasteBin
    description: "Zero's Pastebin."
    url: 'https://iamzlnk.xyz/'
    method: GET
    expectStatus: 200
    
  - id: itssoap-ninja
    name: Soap Ongoing 2
    description: "Soap's Index 1."
    url: 'https://itssoap.ninja/'
    method: GET
    expectStatus: 200

  - id: teamdrive-soap-workers-dev
    name: Soap Ongoing 1
    description: "Soap's Index 2."
    url: 'https://teamdrive.soap.workers.dev/'
    method: GET
    expectStatus: 200
    
  - id: bd-soap-workers-dev
    name: SoapBD
    description: "Soap's BD Index."
    url: 'https://bd.soap.workers.dev/'
    method: GET
    expectStatus: 200
    
  - id: jfofbz-deta-dev
    name: Batch API
    description: "Soap's Batch API."
    url: 'https://jfofbz.deta.dev/'
    method: GET
    expectStatus: 200
  
  - id: afu99e-deta-dev
    name: Mirror API
    description: "Soap's Mirror API."
    url: 'https://afu99e.deta.dev/'
    method: GET
    expectStatus: 200
