settings:
  title: "Status"
  url: 'https://status.itssoap.ninja' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: anidl-org # unique identifier
    name: AniDL
    description: 'AniDL main website.' # default=empty
    url: 'https://anidl.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: magnet
    name: Nyaa-Magnet
    description: "Returns Magnet link from Hash, used by Nyaa RSS"
    url: 'https://hash.soap.workers.dev'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: alc
    name: Alchemist-Index
    description: "Alchemist Index Backend"
    url: 'https://alchemist.itssoap.ninja/'
    method: GET
    expectStatus: 200

  - id: stuff
    name: My-drive
    description: "My drive"
    url: 'https://drivez.itssoap.ninja/'
    method: GET
    expectStatus: 200
